### ISSUE TITLE
creature type ?

### ISSUE THREAD

**Issue by terefang** [PeterRudin-Burgess/Bare-Metal-Edition#4]
| Type | OBi | OBm | AT | DBi | DBm | HTi | HTm |
|:------------------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Aberration | 2.0 | 0.75 | No Armor | 6.0 | 1.0 | 4.0 | 0.8 |
| Animal | 2.0 | 0.75 | No Armor | 6.0 | 1.0 | 4.0 | 0.8 |
| Construct | 1.0 | 1.0 | No Armor | 6.0 | 1.0 | 4.0 | 1.0 |
| Dragon | 1.0 | 1.0 | Heavy | 6.0 | 1.0 | 3.0 | 2.0 |
| Fey | 3.0 | 0.5 | No Armor | 6.0 | 1.0 | 4.0 | 0.6 |
| Humanoid | 2.0 | 0.75 | No Armor | 7.0 | 1.0 | 4.0 | 0.8 |
| Magical-Beast | 1.0 | 1.0 | No Armor | 6.0 | 1.0 | 4.0 | 1.0 |
| Monstrous-Humanoid | 1.0 | 1.0 | No Armor | 6.0 | 1.0 | 4.0 | 1.0 |
| Ooze | 2.0 | 0.75 | No Armor | 6.0 | 1.0 | 4.0 | 0.8 |
| Outsider | 1.0 | 1.0 | No Armor | 6.0 | 1.0 | 4.0 | 1.0 |
| Plant | 2.0 | 0.75 | No Armor | 6.0 | 1.0 | 4.0 | 0.8 |
| Undead | 2.0 | 0.75 | No Armor | 6.0 | 1.0 | 4.0 | 0.8 |
| Vermin | 2.0 | 0.75 | No Armor | 6.0 | 1.0 | 4.0 | 0.8 |

me thinks the armor-types need tuning ...

* Aberration ... at least light armor
* Animal ... at least light armor
* Construct ... at least medium armor 
* Magical-Beast ... at least light armor
* Vermin ... at least light armor

**Comment by terefang** [comment]
| Type | OBi | OBm | AT | DBi | DBm | HTi | HTm |
|:------------------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Aberration | 2 | 0.75 | Light | 6 | 1.0 | 4 | 0.8 |
| Animal | 2 | 0.75 | Light | 6 | 1.0 | 4 | 0.8 |
| Construct | 1 | 1.0 | Medium | 6 | 1.0 | 4 | 1.0 |
| Dragon | 1 | 1.0 | Heavy | 6 | 1.0 | 3 | 2.0 |
| Fey | 3 | 0.5 | No Armor | 6 | 1.0 | 4 | 0.6 |
| Humanoid | 2 | 0.75 | No Armor | 7 | 1.0 | 4 | 0.8 |
| Magical-Beast | 1 | 1.0 | Medium | 6 | 1.0 | 4 | 1.0 |
| Monstrous-Humanoid | 1 | 1.0 | No Armor | 6 | 1.0 | 4 | 1.0 |
| Ooze | 2 | 0.75 | No Armor | 6 | 1.0 | 4 | 0.8 |
| Outsider | 1 | 1.0 | No Armor | 6 | 1.0 | 4 | 1.0 |
| Plant | 2 | 0.75 | No Armor | 6 | 1.0 | 4 | 0.8 |
| Undead | 2 | 0.75 | No Armor | 6 | 1.0 | 4 | 0.8 |
| Vermin | 2 | 0.75 | Light | 6 | 1.0 | 4 | 0.8 |

**Comment by terefang** [comment]
maybe we should define a secondary OB (also tertiary ?)

the second can be used for ranged or ability or vis-versa

| Type | OBi | OBm | OB2i | OB2m | AT | DBi | DBm | HTi | HTm |
|:------------------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Dragon | 1 | 1.0 | 2 | 1.0 | Heavy | 6 | 1.0 | 3 | 2.0 |


| Dragon Size | LE | OB | OB2 | AT | DB | Hits |
|:------------------|:------:|:------:|:------:|:------:|:------:|:------:|
|Fine | 11 | 43 | 35 | Heavy| 53 | 33 |
|Diminutive | 11 | 63 | 55 | Heavy| 33 | 44 |
|Tiny | 11 | 73 | 65 | Heavy| 23 | 67 |
|Small | 11 | 78 | 70 | Heavy| 18 | 93 |
|Medium | 11 | 83 | 75 | Heavy| 13 | 134 |
|Large | 11 | 88 | 80 | Heavy| 8 | 201 |
|Huge | 11 | 93 | 85 | Heavy| 3 | 268 |
|Gargantuan | 11 | 103 | 95 | Heavy| -7 | 402 |
|Colossal | 11 | 123 | 115 | Heavy| -27 | 536 |
|Titanic | 11 | 163 | 155 | Heavy| -67 | 804 |

**Comment by PeterRudin-Burgess** [comment]
We definitely need the secondary and tertiary OBs, many creatures have multiple attack profiles.
This looks like good stuff.

**Comment by terefang** [comment]
ok

| Type | OBi | OBm | OB2i | OB2m | OB3i | OB3m | OB4i | OB4m | AT | DBi | DBm | HTi | HTm |
|:------------------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Aberration | 2 | 1.0 | 3 | 1.0 | 4 | 1.0 | 5 | 1.0 | Light | 6 | 1.0 | 4 | 0.8 |
| Animal | 2 | 0.75 | 3 | 0.77 | 4 | 0.79 | 5 | 0.81 | Light | 6 | 1.0 | 4 | 0.8 |
| Construct | 1 | 1.0 | 2 | 1.0 | 3 | 1.0 | 4 | 1.0 | Medium | 6 | 1.0 | 4 | 1.0 |
| Dragon | 1 | 1.0 | 2 | 1.0 | 3 | 1.0 | 4 | 1.0 | Heavy | 6 | 1.0 | 3 | 2.0 |
| Fey | 3 | 0.5 | 4 | 0.55 | 5 | 0.6 | 6 | 0.65 | No Armor | 6 | 1.0 | 4 | 0.6 |
| Humanoid | 2 | 0.75 | 3 | 0.8 | 4 | 0.9 | 5 | 1.0 | No Armor | 7 | 1.0 | 4 | 0.8 |
| Magical-Beast | 1 | 1.0 | 2 | 1.0 | 3 | 1.0 | 4 | 1.0 | Medium | 6 | 1.0 | 4 | 1.0 |
| Monstrous-Humanoid | 1 | 1.0 | 2 | 1.0 | 3 | 1.0 | 4 | 1.0 | No Armor | 6 | 1.0 | 4 | 1.0 |
| Ooze | 2 | 0.75 | 3 | 0.8 | 4 | 0.9 | 5 | 1.0 | No Armor | 6 | 1.0 | 4 | 0.8 |
| Outsider | 1 | 1.0 | 2 | 1.0 | 3 | 1.0 | 4 | 1.0 | No Armor | 6 | 1.0 | 4 | 1.0 |
| Plant | 2 | 0.75 | 3 | 0.8 | 4 | 0.9 | 5 | 1.0 | No Armor | 6 | 1.0 | 4 | 0.8 |
| Undead | 2 | 0.75 | 3 | 0.8 | 4 | 0.9 | 5 | 1.0 | No Armor | 6 | 1.0 | 4 | 0.8 |
| Vermin | 2 | 0.75 | 3 | 0.8 | 4 | 0.9 | 5 | 1.0 | Light | 6 | 1.0 | 4 | 0.8 |

**Comment by terefang** [comment]
| Dragon Size | LE | OB | OB2 | OB3 | OB4 | AT | DB | Hits |
|:------------------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|Fine | 11 | 43 | 35 | 27 | 14 | Heavy| 53 | 33 |
|Diminutive | 11 | 63 | 55 | 47 | 34 | Heavy| 33 | 44 |
|Tiny | 11 | 73 | 65 | 57 | 44 | Heavy| 23 | 67 |
|Small | 11 | 78 | 70 | 62 | 49 | Heavy| 18 | 93 |
|Medium | 11 | 83 | 75 | 67 | 54 | Heavy| 13 | 134 |
|Large | 11 | 88 | 80 | 72 | 59 | Heavy| 8 | 201 |
|Huge | 11 | 93 | 85 | 77 | 64 | Heavy| 3 | 268 |
|Gargantuan | 11 | 103 | 95 | 87 | 74 | Heavy| -7 | 402 |
|Colossal | 11 | 123 | 115 | 107 | 94 | Heavy| -27 | 536 |
|Titanic | 11 | 163 | 155 | 147 | 134 | Heavy| -67 | 804 |

**Comment by terefang** [comment]
seam we have final
